### ISSUE TITLE
long options with separator return difference result.

### ISSUE THREAD

**Issue by amsitlab** [ncopa/lua-optarg#4]
Passing long option(s) after [ARG ...]
```program arg1 --long-opt=value``` (ok)

Passing long option(s) before [ARG ...]
```program --long-opt=value arg1``` (fail, arg1 not parsed)

Passing long option(s) before [ARG ..] (without separator "=")
```program --long-opt value arg1``` (ok)

It's problem (for end user) when help options message like:

```
Usage: program [options] [args]
     -l, --long-opt=VALUE ...
    .....
```

**Comment by ncopa** [comment]
I believe this was fixed with 7c5ea7222d61e4a874290d1891b5baea41d526c5
